export const content = {
  en: {
    hero: {
      name: 'Miguel Taibo',
      role: 'Software Engineer',
    },
    about: {
      label: 'About me',
      storyLink: 'Full story',
      paragraphs: [
        "Computer Science student at Universidade Da Coruña (UDC)",
        "I've been programming for as long as I can remember, mostly self-taught. It's how I learned to understand how things work under the hood, and to build complete systems on my own. Architecture and backend are where I'm strongest.",
        "I designed TPHome, which now controls the lights and blinds in my house end-to-end with software I built myself. Later, TPCloud brought together several other projects I use daily.",
      ],
    },
    skills: {
      label: 'Tech Stack',
      items: [
        { name: 'Vue', category: 'Frontend' },
        { name: 'Tailwind CSS', category: 'Frontend' },
        { name: 'JavaScript', category: 'Language' },
        { name: 'Python', category: 'Backend' },
        { name: 'FastAPI', category: 'Backend' },
        { name: 'C / C++', category: 'Systems' },
        { name: 'Nix', category: 'DevOps' },
        { name: 'MQTT', category: 'IoT' },
        { name: 'Git', category: 'Tools' },
        { name: 'PlatformIO', category: 'Embedded' },
        { name: 'Cloudflare', category: 'Infra' },
        { name: 'Linux', category: 'Systems' },
      ],
    },
    projects: {
      label: 'Projects',
      items: [
        {
          id: 'tphome',
          name: 'TPHome',
          description: 'Self-hosted home automation system built from scratch. Custom firmware for ESP devices, FastAPI backend on a Raspberry Pi, and a Vue frontend — all running on a local network with MQTT orchestration.',
          tech: ['Vue', 'FastAPI', 'C++', 'MQTT', 'PlatformIO'],
          route: '/tphome',
        },
        {
          id: 'hackudc26',
          name: 'HackUDC 2026 — Inditex Challenge',
          description: 'Visual clothing search engine using CLIP and FAISS embeddings. Built during a 48-hour hackathon as part of the Inditex AI challenge at the Faculty of Computer Science (UDC).',
          tech: ['Python', 'CLIP', 'FAISS', 'Jupyter'],
          route: '/hackudc26',
        },
        {
          id: 'dotfiles',
          name: 'Dotfiles',
          description: 'Fully reproducible development environment managed with Nix flakes. One command sets up my MacBook, NixOS desktop, and Raspberry Pi — same shell, same editor, same tools.',
          tech: ['Nix', 'NixOS', 'Nix Darwin'],
          route: '/dotfiles',
        },
      ],
    },
    contact: {
      label: 'Contact',
      heading: "Let's talk.",
      subheading: "I'm always open to new opportunities, collaborations, or just a good conversation about tech.",
      email: 'contact@migueltaibo.com',
      copyright: '© 2026 Miguel Taibo',
    },
    story: {
      backToHome: 'Back to home',
      heading: 'My full story',
      subheading: 'From LEGO sets to distributed systems.',
      entries: [
        {
          era: 'Early childhood',
          title: 'Builder by nature',
          body: "Before I ever touched a computer, I was obsessed with building things. I spent my afternoons constructing LEGO sets piece by piece — whatever the size, I'd finish them in a single sitting. I told everyone I wanted to be an inventor.",
        },
        {
          era: 'Primary school',
          title: 'Scratch & robotics',
          body: "At school I got my first taste of programming through Scratch, and started going to robotics classes — USB drive in hand — to program things on the school computers. I visited MUNCIT in A Coruña to see real robots. I loved it. At home I kept making little Scratch projects just for fun.",
        },
        {
          era: 'Age 12',
          title: 'Python & Mastermind',
          body: "The summer I turned 12, I found Nate Gentile on YouTube and discovered his Mastermind Academy. I started his Python course and was immediately hooked — no AI, no shortcuts, just raw code. I spent hours programming every day.",
        },
        {
          era: 'Age 12 — same summer',
          title: 'Cybersecurity, Linux & the terminal',
          body: "Right after Python, I took Savitar's cybersecurity course on Mastermind. It opened up a whole new world: Linux, networking, virtual machines, terminal customization. I was twelve years old and already spinning up VMs and reading man pages.",
        },
        {
          era: 'Age 15–16',
          title: 'Web development & the backend pull',
          body: "In my third and fourth year of secondary school I picked up HTML, CSS, and JavaScript — mostly through Dalto's YouTube tutorials. I built simple calculators and small websites. Other creators like Hola Mundo and Midu Dev deepened my understanding of the web, and it became clear that what I actually loved was the backend: the logic, the architecture, the systems underneath.",
        },
        {
          era: 'Bachillerato',
          title: 'Head down, eyes on the goal',
          body: "I stepped back from personal projects to focus on my university entrance exams. The goal was clear: Computer Science at UDC. This was also when AI started appearing everywhere — I began tinkering with it early, long before it became mainstream.",
        },
        {
          era: 'Age 18 — University, year 1',
          title: 'TPHome',
          body: "I started my Computer Science degree at Universidade Da Coruña and, in parallel, began TPHome. I designed the firmware, the backend, and the frontend entirely from scratch. Today it controls the lights and blinds in my house — end-to-end, with software I wrote myself.",
        },
        {
          era: 'Age 19',
          title: 'TPCloud',
          body: "This summer I started TPCloud, a platform that brings together several of the projects I use daily. It's the most ambitious thing I've built so far — and I'm not done yet.",
        },
      ],
    },
    projectDetail: {
      backToHome: 'Back to home',
      overview: 'Overview',
      features: 'Key Features',
      architecture: 'Architecture',
      challenges: 'Challenges & Learnings',
      viewOnGitHub: 'View on GitHub',
      projects: {
        tphome: {
          name: 'TPHome',
          description: 'Self-hosted home automation system built from scratch. Custom firmware for ESP devices, FastAPI backend on a Raspberry Pi, and a Vue frontend — all running on a local network with MQTT orchestration.',
          tech: ['Vue', 'FastAPI', 'C++', 'MQTT', 'PlatformIO'],
          github: 'https://github.com/mtaibo/tphome',
          overview: 'TPHome is a complete home automation solution designed to run entirely on a local network without any cloud dependencies. The system consists of custom ESP32/ESP8266 firmware, a FastAPI backend running on a Raspberry Pi, and a Vue.js frontend for control and monitoring.',
          features: [
            'Custom C++ firmware for ESP32/ESP8266 devices with OTA updates',
            'MQTT-based communication for real-time device control',
            'FastAPI backend with REST API and WebSocket support',
            'Vue.js dashboard with real-time device status',
            'Local network only — no cloud dependencies',
            'Support for multiple sensor types and actuators',
          ],
          architecture: 'The system follows a hub-and-spoke architecture with the Raspberry Pi acting as the central hub. ESP devices connect via MQTT to publish sensor data and receive commands. The FastAPI backend handles business logic and persistence, while the Vue frontend provides the user interface.',
          challenges: 'Building a reliable IoT system from scratch taught me a lot about embedded systems, network protocols, and real-time communication. The biggest challenge was ensuring reliability and handling edge cases like network interruptions and device reconnections.',
        },
        hackudc26: {
          name: 'HackUDC 2026 — Inditex Challenge',
          description: 'Visual clothing search engine using CLIP and FAISS embeddings. Built during a 48-hour hackathon as part of the Inditex AI challenge at the Faculty of Computer Science (UDC).',
          tech: ['Python', 'CLIP', 'FAISS', 'Jupyter'],
          github: 'https://github.com/mtaibo/hackUDC26_reto_inditex',
          overview: "A visual search engine for clothing items that uses OpenAI's CLIP model to generate embeddings and FAISS for efficient similarity search. Users can upload an image of clothing and find visually similar items from a catalog.",
          features: [
            'CLIP model for generating image embeddings',
            'FAISS index for fast similarity search',
            'Support for multiple image formats',
            'Real-time search results',
            'Built in 48 hours during a hackathon',
          ],
          architecture: "The system pre-computes CLIP embeddings for the entire clothing catalog and stores them in a FAISS index. At query time, the user's image is embedded using the same CLIP model, and FAISS performs an approximate nearest neighbor search to find the most similar items.",
          challenges: 'The main challenge was optimizing the embedding computation and search to work within the hackathon time constraints while maintaining good accuracy. We also had to handle various image qualities and styles.',
        },
        dotfiles: {
          name: 'Dotfiles',
          description: 'Fully reproducible development environment managed with Nix flakes. One command sets up my MacBook, NixOS desktop, and Raspberry Pi — same shell, same editor, same tools.',
          tech: ['Nix', 'NixOS', 'Nix Darwin'],
          github: 'https://github.com/mtaibo/dotfiles',
          overview: 'A declarative, reproducible development environment configuration using Nix flakes. The same configuration sets up multiple machines (MacBook, NixOS desktop, Raspberry Pi) with identical tools, shell, and editor setup.',
          features: [
            'Nix flakes for reproducible builds',
            'Cross-platform support (macOS, NixOS, Raspberry Pi)',
            'Declarative system configuration',
            'Home-manager for user environment',
            'Neovim configuration with LSP support',
            'Custom shell setup with zsh and useful aliases',
          ],
          architecture: 'The configuration uses Nix flakes as the entry point, with separate modules for each machine type. Home-manager handles user-level configuration, while system-level configuration is handled by NixOS or nix-darwin depending on the platform.',
          challenges: "The biggest challenge was creating a configuration that works seamlessly across different platforms while maintaining a single source of truth. Nix's declarative nature made this possible, but required careful planning of the module structure.",
        },
      },
    },
  },

  es: {
    hero: {
      name: 'Miguel Taibo',
      role: 'Ingeniero de Software',
    },
    about: {
      label: 'Sobre mí',
      storyLink: 'Mi historia completa',
      paragraphs: [
        'Estudiante de Ingeniería Informática en la Universidade Da Coruña',
        'Programo desde que tengo memoria, de forma autodidacta. La programación me ha servido para entender cómo funcionan las cosas por dentro y construir sistemas completos por mí mismo. La arquitectura y el backend son mi fuerte.',
        'Diseñé TPHome, con el que controlo las luces y persianas de mi casa con software propio de principio a fin. Después, TPCloud integró otros proyectos que uso a diario.'
      ],
    },
    skills: {
      label: 'Stack Tecnológico',
      items: [
        { name: 'Vue', category: 'Frontend' },
        { name: 'Tailwind CSS', category: 'Frontend' },
        { name: 'JavaScript', category: 'Lenguaje' },
        { name: 'Python', category: 'Backend' },
        { name: 'FastAPI', category: 'Backend' },
        { name: 'C / C++', category: 'Sistemas' },
        { name: 'Nix', category: 'DevOps' },
        { name: 'MQTT', category: 'IoT' },
        { name: 'Git', category: 'Herramientas' },
        { name: 'PlatformIO', category: 'Embebido' },
        { name: 'Cloudflare', category: 'Infraestructura' },
        { name: 'Linux', category: 'Sistemas' },
      ],
    },
    projects: {
      label: 'Proyectos',
      items: [
        {
          id: 'tphome',
          name: 'TPHome',
          description: 'Sistema de domótica autoalojado construido desde cero. Firmware personalizado para dispositivos ESP, backend FastAPI en una Raspberry Pi y frontend Vue — todo en red local con orquestación MQTT.',
          tech: ['Vue', 'FastAPI', 'C++', 'MQTT', 'PlatformIO'],
          route: '/tphome',
        },
        {
          id: 'hackudc26',
          name: 'HackUDC 2026 — Reto Inditex',
          description: 'Motor de búsqueda visual de ropa usando embeddings CLIP y FAISS. Desarrollado en un hackathon de 48 horas como parte del reto de IA de Inditex en la Facultad de Informática (UDC).',
          tech: ['Python', 'CLIP', 'FAISS', 'Jupyter'],
          route: '/hackudc26',
        },
        {
          id: 'dotfiles',
          name: 'Dotfiles',
          description: 'Entorno de desarrollo totalmente reproducible gestionado con Nix flakes. Un comando configura mi MacBook, mi escritorio NixOS y mi Raspberry Pi — mismo shell, mismo editor, mismas herramientas.',
          tech: ['Nix', 'NixOS', 'Nix Darwin'],
          route: '/dotfiles',
        },
      ],
    },
    contact: {
      label: 'Contacto',
      heading: 'Hablemos.',
      subheading: 'Siempre estoy abierto a nuevas oportunidades, colaboraciones o simplemente una buena conversación sobre tecnología.',
      email: 'contact@migueltaibo.com',
      copyright: '© 2026 Miguel Taibo',
    },
    story: {
      backToHome: 'Volver al inicio',
      heading: 'Mi historia completa',
      subheading: 'De juegos de LEGO a sistemas distribuidos.',
      entries: [
        {
          era: 'Primera infancia',
          title: 'Constructor de nacimiento',
          body: 'Antes de tocar un ordenador, estaba obsesionado con construir cosas. Pasaba las tardes montando sets de LEGO pieza a pieza — fuera cual fuera el tamaño, los terminaba en una sola sentada. Le decía a todo el mundo que quería ser inventor.',
        },
        {
          era: 'Primaria',
          title: 'Scratch y robótica',
          body: 'En el colegio tuve mi primer contacto con la programación a través de Scratch, y empecé a ir a clases de robótica — USB en mano — para programar en los ordenadores del cole. Visité el MUNCIT en A Coruña para ver robots de verdad. Me encantó. En casa seguía haciendo proyectillos en Scratch por pura diversión.',
        },
        {
          era: '12 años',
          title: 'Python y Mastermind',
          body: 'El verano que cumplí 12 años encontré a Nate Gentile en YouTube y descubrí su academia Mastermind. Empecé su curso de Python y me enganchó de inmediato — sin IA, sin atajos, solo código. Pasaba horas programando cada día.',
        },
        {
          era: '12 años — ese mismo verano',
          title: 'Ciberseguridad, Linux y la terminal',
          body: 'Justo después de Python, hice el curso de ciberseguridad de Savitar en Mastermind. Se abrió un mundo entero: Linux, redes, máquinas virtuales, personalización de la terminal. Tenía doce años y ya levantaba VMs y leía páginas de man.',
        },
        {
          era: '15–16 años',
          title: 'Desarrollo web y la llamada del backend',
          body: 'En tercero y cuarto de la ESO empecé con HTML, CSS y JavaScript — sobre todo con tutoriales de Dalto en YouTube. Hice calculadoras sencillas y webs pequeñas. Otros como Hola Mundo y Midu Dev me profundizaron en el mundo web, y quedó claro que lo que realmente me gustaba era el backend: la lógica, la arquitectura, los sistemas por debajo.',
        },
        {
          era: 'Bachillerato',
          title: 'Cabeza agachada, vista en el objetivo',
          body: 'Dejé de lado los proyectos personales para centrarme en la selectividad. El objetivo era claro: Ingeniería Informática en la UDC. También fue la época en la que la IA empezó a aparecer por todos lados — empecé a trastear con ella pronto, mucho antes de que se pusiera de moda.',
        },
        {
          era: '18 años — 1.º de carrera',
          title: 'TPHome',
          body: 'Empecé Ingeniería Informática en la Universidade Da Coruña y, en paralelo, comencé TPHome. Diseñé el firmware, el backend y el frontend completamente desde cero. Hoy controla las luces y las persianas de mi casa — de principio a fin, con software que escribí yo mismo.',
        },
        {
          era: '19 años',
          title: 'TPCloud',
          body: 'Este verano empecé TPCloud, una plataforma que integra varios de los proyectos que uso a diario. Es lo más ambicioso que he construido hasta ahora — y todavía no he terminado.',
        },
      ],
    },
    projectDetail: {
      backToHome: 'Volver al inicio',
      overview: 'Descripción general',
      features: 'Características principales',
      architecture: 'Arquitectura',
      challenges: 'Retos y aprendizajes',
      viewOnGitHub: 'Ver en GitHub',
      projects: {
        tphome: {
          name: 'TPHome',
          description: 'Sistema de domótica autoalojado construido desde cero. Firmware personalizado para dispositivos ESP, backend FastAPI en una Raspberry Pi y frontend Vue — todo en red local con orquestación MQTT.',
          tech: ['Vue', 'FastAPI', 'C++', 'MQTT', 'PlatformIO'],
          github: 'https://github.com/mtaibo/tphome',
          overview: 'TPHome es una solución completa de domótica diseñada para funcionar íntegramente en red local sin ninguna dependencia en la nube. El sistema consta de firmware personalizado para ESP32/ESP8266, un backend FastAPI en una Raspberry Pi y un frontend Vue.js para control y monitorización.',
          features: [
            'Firmware C++ personalizado para ESP32/ESP8266 con actualizaciones OTA',
            'Comunicación basada en MQTT para control de dispositivos en tiempo real',
            'Backend FastAPI con API REST y soporte WebSocket',
            'Dashboard Vue.js con estado de dispositivos en tiempo real',
            'Solo red local — sin dependencias en la nube',
            'Soporte para múltiples tipos de sensores y actuadores',
          ],
          architecture: 'El sistema sigue una arquitectura en estrella con la Raspberry Pi como nodo central. Los dispositivos ESP se conectan via MQTT para publicar datos de sensores y recibir comandos. El backend FastAPI gestiona la lógica de negocio y la persistencia, mientras que el frontend Vue proporciona la interfaz de usuario.',
          challenges: 'Construir un sistema IoT fiable desde cero me enseñó mucho sobre sistemas embebidos, protocolos de red y comunicación en tiempo real. El mayor reto fue garantizar la fiabilidad y gestionar casos límite como interrupciones de red y reconexiones de dispositivos.',
        },
        hackudc26: {
          name: 'HackUDC 2026 — Reto Inditex',
          description: 'Motor de búsqueda visual de ropa usando embeddings CLIP y FAISS. Desarrollado en un hackathon de 48 horas como parte del reto de IA de Inditex en la Facultad de Informática (UDC).',
          tech: ['Python', 'CLIP', 'FAISS', 'Jupyter'],
          github: 'https://github.com/mtaibo/hackUDC26_reto_inditex',
          overview: 'Un motor de búsqueda visual de prendas de ropa que usa el modelo CLIP de OpenAI para generar embeddings y FAISS para búsqueda eficiente por similitud. Los usuarios pueden subir una imagen de ropa y encontrar artículos visualmente similares en un catálogo.',
          features: [
            'Modelo CLIP para generar embeddings de imágenes',
            'Índice FAISS para búsqueda rápida por similitud',
            'Soporte para múltiples formatos de imagen',
            'Resultados de búsqueda en tiempo real',
            'Desarrollado en 48 horas durante un hackathon',
          ],
          architecture: 'El sistema precalcula los embeddings CLIP para todo el catálogo de ropa y los almacena en un índice FAISS. En tiempo de consulta, la imagen del usuario se embebe con el mismo modelo CLIP y FAISS realiza una búsqueda aproximada de vecinos más cercanos para encontrar los artículos más similares.',
          challenges: 'El principal reto fue optimizar el cómputo de embeddings y la búsqueda para cumplir los plazos del hackathon manteniendo una buena precisión. También tuvimos que manejar imágenes de distintas calidades y estilos.',
        },
        dotfiles: {
          name: 'Dotfiles',
          description: 'Entorno de desarrollo totalmente reproducible gestionado con Nix flakes. Un comando configura mi MacBook, mi escritorio NixOS y mi Raspberry Pi — mismo shell, mismo editor, mismas herramientas.',
          tech: ['Nix', 'NixOS', 'Nix Darwin'],
          github: 'https://github.com/mtaibo/dotfiles',
          overview: 'Una configuración de entorno de desarrollo declarativa y reproducible usando Nix flakes. La misma configuración inicializa múltiples máquinas (MacBook, escritorio NixOS, Raspberry Pi) con herramientas, shell y editor idénticos.',
          features: [
            'Nix flakes para builds reproducibles',
            'Soporte multiplataforma (macOS, NixOS, Raspberry Pi)',
            'Configuración de sistema declarativa',
            'Home-manager para el entorno de usuario',
            'Configuración de Neovim con soporte LSP',
            'Configuración de shell personalizada con zsh y alias útiles',
          ],
          architecture: 'La configuración usa Nix flakes como punto de entrada, con módulos separados para cada tipo de máquina. Home-manager gestiona la configuración a nivel de usuario, mientras que la configuración a nivel de sistema la gestionan NixOS o nix-darwin según la plataforma.',
          challenges: 'El mayor reto fue crear una configuración que funcionara fluidamente en distintas plataformas manteniendo una única fuente de verdad. La naturaleza declarativa de Nix lo hizo posible, pero requirió una planificación cuidadosa de la estructura de módulos.',
        },
      },
    },
  },
}
