export const content = {
  en: {
    hero: {
      name: 'Miguel Taibo',
      role: 'Software Engineer',
    },
    about: {
      label: 'About me',
      paragraphs: [
        "Second year Computer Science student at Universidad De Coruña (UDC)",
        "I've always been curious about how things work, which led me to become a self-taught full-stack developer. I love the process of building systems from the ground up and solving problems through code.",
        "I'm currently looking for new challenges to help me grow as a developer and reach my career goals."
      ],
    },
    skills: {
      label: 'Tech Stack',
      items: [
        { name: 'Vue', category: 'Frontend' },
        { name: 'Tailwind CSS', category: 'Frontend' },
        { name: 'JavaScript', category: 'Language' },
        { name: 'Python', category: 'Backend' },
        { name: 'FastAPI', category: 'Backend' },
        { name: 'C / C++', category: 'Systems' },
        { name: 'Nix', category: 'DevOps' },
        { name: 'MQTT', category: 'IoT' },
        { name: 'Git', category: 'Tools' },
        { name: 'PlatformIO', category: 'Embedded' },
        { name: 'Cloudflare', category: 'Infra' },
        { name: 'Linux', category: 'Systems' },
      ],
    },
    projects: {
      label: 'Projects',
      items: [
        {
          id: 'tphome',
          name: 'TPHome',
          description: 'Self-hosted home automation system built from scratch. Custom firmware for ESP devices, FastAPI backend on a Raspberry Pi, and a Vue frontend — all running on a local network with MQTT orchestration.',
          tech: ['Vue', 'FastAPI', 'C++', 'MQTT', 'PlatformIO'],
          route: '/tphome',
        },
        {
          id: 'hackudc26',
          name: 'HackUDC 2026 — Inditex Challenge',
          description: 'Visual clothing search engine using CLIP and FAISS embeddings. Built during a 48-hour hackathon as part of the Inditex AI challenge at the Faculty of Computer Science (UDC).',
          tech: ['Python', 'CLIP', 'FAISS', 'Jupyter'],
          route: '/hackudc26',
        },
        {
          id: 'dotfiles',
          name: 'Dotfiles',
          description: 'Fully reproducible development environment managed with Nix flakes. One command sets up my MacBook, NixOS desktop, and Raspberry Pi — same shell, same editor, same tools.',
          tech: ['Nix', 'NixOS', 'Nix Darwin'],
          route: '/dotfiles',
        },
      ],
    },
    contact: {
      label: 'Contact',
      heading: "Let's talk.",
      subheading: "I'm always open to new opportunities, collaborations, or just a good conversation about tech.",
      email: 'contact@migueltaibo.com',
      copyright: '© 2026 Miguel Taibo',
    },
    projectDetail: {
      backToHome: 'Back to home',
      overview: 'Overview',
      features: 'Key Features',
      architecture: 'Architecture',
      challenges: 'Challenges & Learnings',
      viewOnGitHub: 'View on GitHub',
      projects: {
        tphome: {
          name: 'TPHome',
          description: 'Self-hosted home automation system built from scratch. Custom firmware for ESP devices, FastAPI backend on a Raspberry Pi, and a Vue frontend — all running on a local network with MQTT orchestration.',
          tech: ['Vue', 'FastAPI', 'C++', 'MQTT', 'PlatformIO'],
          github: 'https://github.com/mtaibo/tphome',
          overview: 'TPHome is a complete home automation solution designed to run entirely on a local network without any cloud dependencies. The system consists of custom ESP32/ESP8266 firmware, a FastAPI backend running on a Raspberry Pi, and a Vue.js frontend for control and monitoring.',
          features: [
            'Custom C++ firmware for ESP32/ESP8266 devices with OTA updates',
            'MQTT-based communication for real-time device control',
            'FastAPI backend with REST API and WebSocket support',
            'Vue.js dashboard with real-time device status',
            'Local network only — no cloud dependencies',
            'Support for multiple sensor types and actuators',
          ],
          architecture: 'The system follows a hub-and-spoke architecture with the Raspberry Pi acting as the central hub. ESP devices connect via MQTT to publish sensor data and receive commands. The FastAPI backend handles business logic and persistence, while the Vue frontend provides the user interface.',
          challenges: 'Building a reliable IoT system from scratch taught me a lot about embedded systems, network protocols, and real-time communication. The biggest challenge was ensuring reliability and handling edge cases like network interruptions and device reconnections.',
        },
        hackudc26: {
          name: 'HackUDC 2026 — Inditex Challenge',
          description: 'Visual clothing search engine using CLIP and FAISS embeddings. Built during a 48-hour hackathon as part of the Inditex AI challenge at the Faculty of Computer Science (UDC).',
          tech: ['Python', 'CLIP', 'FAISS', 'Jupyter'],
          github: 'https://github.com/mtaibo/hackUDC26_reto_inditex',
          overview: "A visual search engine for clothing items that uses OpenAI's CLIP model to generate embeddings and FAISS for efficient similarity search. Users can upload an image of clothing and find visually similar items from a catalog.",
          features: [
            'CLIP model for generating image embeddings',
            'FAISS index for fast similarity search',
            'Support for multiple image formats',
            'Real-time search results',
            'Built in 48 hours during a hackathon',
          ],
          architecture: "The system pre-computes CLIP embeddings for the entire clothing catalog and stores them in a FAISS index. At query time, the user's image is embedded using the same CLIP model, and FAISS performs an approximate nearest neighbor search to find the most similar items.",
          challenges: 'The main challenge was optimizing the embedding computation and search to work within the hackathon time constraints while maintaining good accuracy. We also had to handle various image qualities and styles.',
        },
        dotfiles: {
          name: 'Dotfiles',
          description: 'Fully reproducible development environment managed with Nix flakes. One command sets up my MacBook, NixOS desktop, and Raspberry Pi — same shell, same editor, same tools.',
          tech: ['Nix', 'NixOS', 'Nix Darwin'],
          github: 'https://github.com/mtaibo/dotfiles',
          overview: 'A declarative, reproducible development environment configuration using Nix flakes. The same configuration sets up multiple machines (MacBook, NixOS desktop, Raspberry Pi) with identical tools, shell, and editor setup.',
          features: [
            'Nix flakes for reproducible builds',
            'Cross-platform support (macOS, NixOS, Raspberry Pi)',
            'Declarative system configuration',
            'Home-manager for user environment',
            'Neovim configuration with LSP support',
            'Custom shell setup with zsh and useful aliases',
          ],
          architecture: 'The configuration uses Nix flakes as the entry point, with separate modules for each machine type. Home-manager handles user-level configuration, while system-level configuration is handled by NixOS or nix-darwin depending on the platform.',
          challenges: "The biggest challenge was creating a configuration that works seamlessly across different platforms while maintaining a single source of truth. Nix's declarative nature made this possible, but required careful planning of the module structure.",
        },
      },
    },
  },

  es: {
    hero: {
      name: 'Miguel Taibo',
      role: 'Ingeniero de Software',
    },
    about: {
      label: 'Sobre mí',
      paragraphs: [
        'Estudiante de segundo año de Ingeniería Informática en la Universidad De Coruña',
        'Mi curiosidad por la tecnología me ha llevado a aprender a desarrollar todo tipo de sistemas completos por mi cuenta, creando distintos proyectos personales desde cero. Me encanta resolver problemas y diseñar soluciones a través del código.', 
        'En este momento me encuentro en busca de nuevos retos que me permitan alcanzar mis metas como desarrollador.'
      ],
    },
    skills: {
      label: 'Stack Tecnológico',
      items: [
        { name: 'Vue', category: 'Frontend' },
        { name: 'Tailwind CSS', category: 'Frontend' },
        { name: 'JavaScript', category: 'Lenguaje' },
        { name: 'Python', category: 'Backend' },
        { name: 'FastAPI', category: 'Backend' },
        { name: 'C / C++', category: 'Sistemas' },
        { name: 'Nix', category: 'DevOps' },
        { name: 'MQTT', category: 'IoT' },
        { name: 'Git', category: 'Herramientas' },
        { name: 'PlatformIO', category: 'Embebido' },
        { name: 'Cloudflare', category: 'Infraestructura' },
        { name: 'Linux', category: 'Sistemas' },
      ],
    },
    projects: {
      label: 'Proyectos',
      items: [
        {
          id: 'tphome',
          name: 'TPHome',
          description: 'Sistema de domótica autoalojado construido desde cero. Firmware personalizado para dispositivos ESP, backend FastAPI en una Raspberry Pi y frontend Vue — todo en red local con orquestación MQTT.',
          tech: ['Vue', 'FastAPI', 'C++', 'MQTT', 'PlatformIO'],
          route: '/tphome',
        },
        {
          id: 'hackudc26',
          name: 'HackUDC 2026 — Reto Inditex',
          description: 'Motor de búsqueda visual de ropa usando embeddings CLIP y FAISS. Desarrollado en un hackathon de 48 horas como parte del reto de IA de Inditex en la Facultad de Informática (UDC).',
          tech: ['Python', 'CLIP', 'FAISS', 'Jupyter'],
          route: '/hackudc26',
        },
        {
          id: 'dotfiles',
          name: 'Dotfiles',
          description: 'Entorno de desarrollo totalmente reproducible gestionado con Nix flakes. Un comando configura mi MacBook, mi escritorio NixOS y mi Raspberry Pi — mismo shell, mismo editor, mismas herramientas.',
          tech: ['Nix', 'NixOS', 'Nix Darwin'],
          route: '/dotfiles',
        },
      ],
    },
    contact: {
      label: 'Contacto',
      heading: 'Hablemos.',
      subheading: 'Siempre estoy abierto a nuevas oportunidades, colaboraciones o simplemente una buena conversación sobre tecnología.',
      email: 'contact@migueltaibo.com',
      copyright: '© 2026 Miguel Taibo',
    },
    projectDetail: {
      backToHome: 'Volver al inicio',
      overview: 'Descripción general',
      features: 'Características principales',
      architecture: 'Arquitectura',
      challenges: 'Retos y aprendizajes',
      viewOnGitHub: 'Ver en GitHub',
      projects: {
        tphome: {
          name: 'TPHome',
          description: 'Sistema de domótica autoalojado construido desde cero. Firmware personalizado para dispositivos ESP, backend FastAPI en una Raspberry Pi y frontend Vue — todo en red local con orquestación MQTT.',
          tech: ['Vue', 'FastAPI', 'C++', 'MQTT', 'PlatformIO'],
          github: 'https://github.com/mtaibo/tphome',
          overview: 'TPHome es una solución completa de domótica diseñada para funcionar íntegramente en red local sin ninguna dependencia en la nube. El sistema consta de firmware personalizado para ESP32/ESP8266, un backend FastAPI en una Raspberry Pi y un frontend Vue.js para control y monitorización.',
          features: [
            'Firmware C++ personalizado para ESP32/ESP8266 con actualizaciones OTA',
            'Comunicación basada en MQTT para control de dispositivos en tiempo real',
            'Backend FastAPI con API REST y soporte WebSocket',
            'Dashboard Vue.js con estado de dispositivos en tiempo real',
            'Solo red local — sin dependencias en la nube',
            'Soporte para múltiples tipos de sensores y actuadores',
          ],
          architecture: 'El sistema sigue una arquitectura en estrella con la Raspberry Pi como nodo central. Los dispositivos ESP se conectan via MQTT para publicar datos de sensores y recibir comandos. El backend FastAPI gestiona la lógica de negocio y la persistencia, mientras que el frontend Vue proporciona la interfaz de usuario.',
          challenges: 'Construir un sistema IoT fiable desde cero me enseñó mucho sobre sistemas embebidos, protocolos de red y comunicación en tiempo real. El mayor reto fue garantizar la fiabilidad y gestionar casos límite como interrupciones de red y reconexiones de dispositivos.',
        },
        hackudc26: {
          name: 'HackUDC 2026 — Reto Inditex',
          description: 'Motor de búsqueda visual de ropa usando embeddings CLIP y FAISS. Desarrollado en un hackathon de 48 horas como parte del reto de IA de Inditex en la Facultad de Informática (UDC).',
          tech: ['Python', 'CLIP', 'FAISS', 'Jupyter'],
          github: 'https://github.com/mtaibo/hackUDC26_reto_inditex',
          overview: 'Un motor de búsqueda visual de prendas de ropa que usa el modelo CLIP de OpenAI para generar embeddings y FAISS para búsqueda eficiente por similitud. Los usuarios pueden subir una imagen de ropa y encontrar artículos visualmente similares en un catálogo.',
          features: [
            'Modelo CLIP para generar embeddings de imágenes',
            'Índice FAISS para búsqueda rápida por similitud',
            'Soporte para múltiples formatos de imagen',
            'Resultados de búsqueda en tiempo real',
            'Desarrollado en 48 horas durante un hackathon',
          ],
          architecture: 'El sistema precalcula los embeddings CLIP para todo el catálogo de ropa y los almacena en un índice FAISS. En tiempo de consulta, la imagen del usuario se embebe con el mismo modelo CLIP y FAISS realiza una búsqueda aproximada de vecinos más cercanos para encontrar los artículos más similares.',
          challenges: 'El principal reto fue optimizar el cómputo de embeddings y la búsqueda para cumplir los plazos del hackathon manteniendo una buena precisión. También tuvimos que manejar imágenes de distintas calidades y estilos.',
        },
        dotfiles: {
          name: 'Dotfiles',
          description: 'Entorno de desarrollo totalmente reproducible gestionado con Nix flakes. Un comando configura mi MacBook, mi escritorio NixOS y mi Raspberry Pi — mismo shell, mismo editor, mismas herramientas.',
          tech: ['Nix', 'NixOS', 'Nix Darwin'],
          github: 'https://github.com/mtaibo/dotfiles',
          overview: 'Una configuración de entorno de desarrollo declarativa y reproducible usando Nix flakes. La misma configuración inicializa múltiples máquinas (MacBook, escritorio NixOS, Raspberry Pi) con herramientas, shell y editor idénticos.',
          features: [
            'Nix flakes para builds reproducibles',
            'Soporte multiplataforma (macOS, NixOS, Raspberry Pi)',
            'Configuración de sistema declarativa',
            'Home-manager para el entorno de usuario',
            'Configuración de Neovim con soporte LSP',
            'Configuración de shell personalizada con zsh y alias útiles',
          ],
          architecture: 'La configuración usa Nix flakes como punto de entrada, con módulos separados para cada tipo de máquina. Home-manager gestiona la configuración a nivel de usuario, mientras que la configuración a nivel de sistema la gestionan NixOS o nix-darwin según la plataforma.',
          challenges: 'El mayor reto fue crear una configuración que funcionara fluidamente en distintas plataformas manteniendo una única fuente de verdad. La naturaleza declarativa de Nix lo hizo posible, pero requirió una planificación cuidadosa de la estructura de módulos.',
        },
      },
    },
  },
}
